### ISSUE TITLE
DietPi-Dashboard | Information Centralization (HUB)

### ISSUE THREAD

**Issue by mknrls** [Fourdee/DietPi-Dashboard#1]
# DietPi-Dashboard (W.I.P)
Just centralizing the information on this repo from https://github.com/Fourdee/DietPi/issues/448
@Fourdee feel free to edit this page at anytime 👍 

## Requirements
**Base:** Must not require a webserver stack (implies self-contained website). 
eg: Websockets and Bootstrap/JS. _`Lightweight (minimal CPU and MEMORY usage)`_

Main DietPi programs for web implementation:
- DietPi-Software
- DietPi-Config

Additional features:
- Terminal window

## Current State:
`Sept 2016` C++ version started. Pull all DietPi-Software data into c++. Software installation possible through it.

**Comment by Fourdee** [comment]
@mknrls 

Thanks 👍 

> C++ version started. Pull all DietPi-Software data into c++. Software installation possible through it.

This was created solely because we were planning to use a C++ web library. However, I can change that for bootstrap/JS.

In short, this is how the web interface would work with ```dietpi-software``` script:
- Run ```/DietPi/dietpi/dietpi-software weblist_export``` to get list of available software, installed states etc.
- That will create files with an export of the data in ```/tmp/dietpi-software/weblist_export/*```, each line is a index of array. eg, 32 = HiFi
- That data then needs to be pulled into the web interface as an array, for each file.

If you need more info, let me know.

**Comment by mknrls** [comment]
@Fourdee 
how about we used nodejs as web server like it is already self-contain (got the idea from volumio). 
now just have to figure out how the data will be pulled to display it in the web interface
